before_script:
  - echo "Before script"
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H 'dvoit.dev' >> ~/.ssh/known_hosts
  - npm install
  - cd /var/www/dvoit.dev #your project path
building:
  stage: build
  script:
    - git reset --hard
    - git pull origin master
    - composer install
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate --seed
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link
    - sudo chown -R deployer:www-data /var/www/dvoit.dev/
    - find /var/www/dvoit.dev -type f -exec chmod 664 {} \;
    - find /var/www/dvoit.dev -type d -exec chmod 775 {} \;
    - chgrp -R www-data storage bootstrap/cache
    - chmod -R ug+rwx storage bootstrap/cache
testing:
  stage: test
  script:
    - php ./vendor/bin/phpunit
deploying:
  stage: deploy
  script:
    - echo "Deployed"
    - php artisan queue:restart #if you use queue