before_script:
  - echo "Before script"
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - chmod 700 ~/.ssh
  - ssh-keyscan dvoit.dev >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - git config --global user.email "dillon.voit@gmail.com"
  - git config --global user.name "Dillon Voit"
  - cd /var/www/dvoit.dev #your project path
building:
  stage: build
  script:
    - git reset --hard
    - git pull origin master
    - composer install
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate --seed
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link
    - sudo chown -R deployer:www-data /var/www/dvoit.dev/
    - find /var/www/dvoit.dev -type f -exec chmod 664 {} \;
    - find /var/www/dvoit.dev -type d -exec chmod 775 {} \;
    - chgrp -R www-data storage bootstrap/cache
    - chmod -R ug+rwx storage bootstrap/cache
testing:
  stage: test
  script:
    - php ./vendor/bin/phpunit
deploying:
  stage: deploy
  script:
    - echo "Deployed"
    - php artisan queue:restart #if you use queue